/** Livros da Bíblia em português do Brasil, com código USFM e variações comuns de escrita. */
export interface BibleBook {
  code: string;
  name: string;
  aliases?: string[];
}

export const BIBLE_BOOKS: BibleBook[] = [
  { code: "GEN", name: "Gênesis" },
  { code: "EXO", name: "Êxodo" },
  { code: "LEV", name: "Levítico" },
  { code: "NUM", name: "Números" },
  { code: "DEU", name: "Deuteronômio" },
  { code: "JOS", name: "Josué" },
  { code: "JDG", name: "Juízes" },
  { code: "RUT", name: "Rute" },
  { code: "1SA", name: "1 Samuel" },
  { code: "2SA", name: "2 Samuel" },
  { code: "1KI", name: "1 Reis" },
  { code: "2KI", name: "2 Reis" },
  { code: "1CH", name: "1 Crônicas" },
  { code: "2CH", name: "2 Crônicas" },
  { code: "EZR", name: "Esdras" },
  { code: "NEH", name: "Neemias" },
  { code: "EST", name: "Ester" },
  { code: "JOB", name: "Jó" },
  { code: "PSA", name: "Salmos", aliases: ["Salmo"] },
  { code: "PRO", name: "Provérbios" },
  { code: "ECC", name: "Eclesiastes" },
  { code: "SNG", name: "Cantares", aliases: ["Cântico dos Cânticos"] },
  { code: "ISA", name: "Isaías" },
  { code: "JER", name: "Jeremias" },
  { code: "LAM", name: "Lamentações" },
  { code: "EZK", name: "Ezequiel" },
  { code: "DAN", name: "Daniel" },
  { code: "HOS", name: "Oseias" },
  { code: "JOL", name: "Joel" },
  { code: "AMO", name: "Amós" },
  { code: "OBA", name: "Obadias" },
  { code: "JON", name: "Jonas" },
  { code: "MIC", name: "Miqueias" },
  { code: "NAM", name: "Naum" },
  { code: "HAB", name: "Habacuque" },
  { code: "ZEP", name: "Sofonias" },
  { code: "HAG", name: "Ageu" },
  { code: "ZEC", name: "Zacarias" },
  { code: "MAL", name: "Malaquias" },
  { code: "MAT", name: "Mateus" },
  { code: "MRK", name: "Marcos" },
  { code: "LUK", name: "Lucas" },
  { code: "JHN", name: "João" },
  { code: "ACT", name: "Atos" },
  { code: "ROM", name: "Romanos" },
  { code: "1CO", name: "1 Coríntios" },
  { code: "2CO", name: "2 Coríntios" },
  { code: "GAL", name: "Gálatas" },
  { code: "EPH", name: "Efésios" },
  { code: "PHP", name: "Filipenses" },
  { code: "COL", name: "Colossenses" },
  { code: "1TH", name: "1 Tessalonicenses" },
  { code: "2TH", name: "2 Tessalonicenses" },
  { code: "1TI", name: "1 Timóteo" },
  { code: "2TI", name: "2 Timóteo" },
  { code: "TIT", name: "Tito" },
  { code: "PHM", name: "Filemom" },
  { code: "HEB", name: "Hebreus" },
  { code: "JAS", name: "Tiago" },
  { code: "1PE", name: "1 Pedro" },
  { code: "2PE", name: "2 Pedro" },
  { code: "1JN", name: "1 João" },
  { code: "2JN", name: "2 João" },
  { code: "3JN", name: "3 João" },
  { code: "JUD", name: "Judas" },
  { code: "REV", name: "Apocalipse" },
];
